### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by olivernyc** [meshcenter/mesh-api#52]
- [ ] Finish endpoints (for updating members, nodes, requests, devices) **Moved to #62**
- [ ] Figure out dashboard editing flow, especially for common tasks like new node after install, adding members to nodes, setting device locations **Moved to #63**
- [ ] Set up db migrations **Moved to #64**
- [ ] Add some tests **Moved to #65**
- [ ] Pagination **Moved to #66**
- [ ] Update map to show data from api **Moved to #67**
- [ ] Panorama upload form (api work is done) **Moved to #68**

**Comment by greenberga** [comment]
Split this issue into smaller issues for each sub-task (links are provided in the body of the issue).
